BLACK   = "\x1b[30m"
RED     = "\x1b[31m"
GREEN   = "\x1b[32m"
YELLOW  = "\x1b[33m"
BLUE    = "\x1b[34m"
MAGENTA = "\x1b[35m"
CYAN    = "\x1b[36m"
RESET   = "\x1b[0m"
BOLD    = "\x1b[1m"
BLACKB  =  BLACK   +   BOLD
REDB    =  RED     +   BOLD
GREENB  =  GREEN   +   BOLD
YELLOWB =  YELLOW  +   BOLD
BLUEB   =  BLUE    +   BOLD
MAGENTAB=  MAGENTA +   BOLD
CYANB   =  CYAN    +   BOLD